// Generated by CoffeeScript 1.3.3
var Queue, display, notify_messages, notify_notifying, publish,
  __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

Queue = (function() {

  function Queue(data) {
    this.data = data != null ? data : [];
    this.size = __bind(this.size, this);

    this.clear = __bind(this.clear, this);

    this.enqueue = __bind(this.enqueue, this);

    this.isEmpty = __bind(this.isEmpty, this);

  }

  Queue.prototype.isEmpty = function() {
    return this.data.length === 0;
  };

  Queue.prototype.enqueue = function(obj) {
    return this.data.push(obj);
  };

  Queue.prototype.last = function() {
    return this.data.shift();
  };

  Queue.prototype.clear = function() {
    return this.data = [];
  };

  Queue.prototype.size = function() {
    return this.data.length;
  };

  return Queue;

})();

notify_messages = new Queue;

notify_notifying = false;

publish = function() {
  var msg;
  notify_notifying = true;
  msg = notify_messages.last();
  return display(msg);
};

display = function(msg) {
  return $(msg.container).queue(function(next) {
    $(this).addClass(msg.messageClass).$[msg.showAnimation]().html(msg.message).delay(msg.timing).$[hideAnimation](function() {
      return $(msg.container).removeClass(msg.messageClass, function() {}, notify_messages.isEmpty() ? notify_notifying = false : (publish(notify_messages), $('.queue span').html(notify_messages.size())));
    });
    return next();
  });
};

$.notify = function(args) {
  var defaults, options;
  defaults = {
    message: 'hello world',
    container: '#notify',
    messageClass: 'success',
    showAnimation: 'slideDown',
    hideAnimation: 'slideUp',
    timing: 1000
  };
  options = $.extend(defaults, args || {});
  if (notify_notifying) {
    return notify_messages.enqueue(options);
  } else {
    notify_messages.enqueue(options);
    return publish(notify_messages);
  }
};
